[project]
name = "mcp-example"
version = "0.1.0"
description = "Example MCP project using uv and pyproject.toml dependencies."
requires-python = ">=3.12"
dependencies = [
  "google-adk==1.19.0",
  "fastmcp==2.13.1"
]

[tool.ruff]
line-length = 120
target-version = "py312"
